### ISSUE TITLE
Error on Bake Action Bakery action

### ISSUE THREAD

**Issue by dovmantov** [BlenderBoi/Game-Rig-Tools#1]
Blnder ver. 3.5.0
When I select my animations from rigify rig to bake into game prepared rig I get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Game-Rig-Tools-master\GRT_Action_Bakery.py", line 855, in execute
    deform_rig.animation_data.nla_tracks.new().strips.new(Baked_Action[0].name, Baked_Action[0].frame_range[0], Baked_Action[0])
TypeError: NlaStrips.new(): error with argument 2, "start" -  Function.start expected an int type, not float

**Comment by dovmantov** [comment]
Here are .blend file https://drive.google.com/file/d/1_o2rKTqNC-quZu3yUuakVr2v7gc8SALl/view?usp=share_link

**Comment by BlenderBoi** [comment]
Are you using the latest version of GRT for this?

**Comment by BlenderBoi** [comment]
Try getting the latest version of GRT and try it and see if it works, If the error still persist, let me know

Remove the Old version of GRT before installing the new one

**Comment by dovmantov** [comment]
New Game Rig Tool ver is 1.6.3?

**Comment by dovmantov** [comment]
Here is what I have:
![image](https://user-images.githubusercontent.com/42407914/232258310-4bfd5667-f438-4f87-af08-541462c7425c.png)

**Comment by dovmantov** [comment]
Okay, i've updated to 1.6.6

![image](https://user-images.githubusercontent.com/42407914/232259340-3fbf700c-8800-482d-8dfe-2ae3b9ce6d18.png)

**Comment by dovmantov** [comment]
Okay, on button "From NLA"  in action bakery animation list I catch this error:

Python: Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Game_Rig_Tools-master\GRT_Action_Bakery.py", line 83, in invoke
    return self.execute(context)
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Game_Rig_Tools-master\GRT_Action_Bakery.py", line 134, in execute
    item.Set_FR_Start = action.frame_range[0]
TypeError: bpy_struct: item.attr = val: GRT_Action_Bakery_Property_Group.Set_FR_Start expected an int type, not float


![image](https://user-images.githubusercontent.com/42407914/232259469-aa8a77bb-6a55-412b-ae7d-aaba20b5736b.png)

**Comment by dovmantov** [comment]
Trying to add one by one.

**Comment by dovmantov** [comment]
Anyway... picked animations to bake into game rig and catched this:

Python: Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Game_Rig_Tools-master\GRT_Action_Bakery.py", line 918, in execute
    deform_rig.animation_data.nla_tracks.new().strips.new(Baked_Action[0].name, Baked_Action[0].frame_range[0], Baked_Action[0])
TypeError: NlaStrips.new(): error with argument 2, "start" -  Function.start expected an int type, not float


![image](https://user-images.githubusercontent.com/42407914/232259633-c42a4c8b-5fd5-46a3-8817-6e5577db0367.png)

**Comment by dovmantov** [comment]
I figured out. If not select "Push in NLA" toggle in acton bakerey section no error hapens. So despite on error I can still use addon.

**Comment by BlenderBoi** [comment]
Hey, Just double checking, because versioning is a little messy on github here. 

Do you get your GRT from github or gumroad (CG Dive Gumroad), the versioning is more.... organized there. ?

If you get from github, try download the 3.3 branch, but if possible, try the latest gumroad latest version first, because that one is more "Official" and sorted out. 

You can download from here... but it is a little messy on github
